In [141]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [142]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [143]:
fake['text'][0]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year!  Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you  Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress.  Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me?  Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish??  Marlene (@marlene399) December 31, 2017You can t just say happy new year?  Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love!  Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his  enemies  and  haters  for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA  Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President?  Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters?  Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old  Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.'

In [144]:
true.shape

(21417, 4)

In [145]:
fake.shape

(23481, 4)

In [146]:
fake['label'] = 'fake'

In [147]:
true['label'] = 'true'

In [148]:
data = pd.concat([true, fake], ignore_index= True)

In [149]:
data['label'].unique()

array(['true', 'fake'], dtype=object)

In [150]:
data.shape

(44898, 5)

In [151]:
data.columns

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [152]:
data.isna().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [153]:
data['content'] = data['text'] +' '+ data['title']

In [154]:
data.head()

,title,text,subject,date,label,content
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",true,WASHINGTON (Reuters) - The head of a conservat...
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",true,WASHINGTON (Reuters) - Transgender people will...
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",true,WASHINGTON (Reuters) - The special counsel inv...
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",true,WASHINGTON (Reuters) - Trump campaign adviser ...
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",true,SEATTLE/WASHINGTON (Reuters) - President Donal...

In [155]:
data['content'] = data['content'].str.lower()

In [156]:
data.head()

,title,text,subject,date,label,content
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",true,washington (reuters) - the head of a conservat...
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",true,washington (reuters) - transgender people will...
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",true,washington (reuters) - the special counsel inv...
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",true,washington (reuters) - trump campaign adviser ...
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",true,seattle/washington (reuters) - president donal...

In [157]:
import string
for char in string.punctuation:
    data['content'] = data['content'].str.replace(char, ' ')

In [158]:
data['content'] = data['content'].str.replace('“', '')
data['content'] = data['content'].str.replace('”', '')
data['content'] = data['content'].str.replace("’", '')
data['content'] = data['content'].str.replace("‘", '')
data['content'] = data['content'].str.replace("'", '')
data['content'] = data['content'].str.replace(",", '')

In [159]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\anz45\miniconda3\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\anz45\miniconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\anz45\miniconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\anz45\miniconda3\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\anz45\miniconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\anz45\miniconda3\lib\site-packages (from click->nltk) (0.4.6)

In [160]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anz45\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [161]:
stopwords = set(stopwords.words('english'))


data['content'] = data['content'].apply( lambda row : ' '.join([word for word in row.split() if word not in stopwords]))

In [162]:
data['content']

0        washington reuters head conservative republica...
1        washington reuters transgender people allowed ...
2        washington reuters special counsel investigati...
3        washington reuters trump campaign adviser geor...
4        seattle washington reuters president donald tr...
                               ...
44893    21st century wire says 21wire reported earlier...
44894    21st century wire says familiar theme whenever...
44895    patrick henningsen 21st century wireremember o...
44896    21st century wire says al jazeera america go h...
44897    21st century wire says 21wire predicted new ye...
Name: content, Length: 44898, dtype: object

In [163]:
data['content'] = data['content'].astype(str)

In [164]:
num_list =['0','1','2','3','4','5','6','7','8','9']

for x in num_list:
    data['content'] = data['content'].str.replace(x, ' ')

In [167]:
from collections import Counter

In [169]:
counter_ = Counter(data['content'])